apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: NAMESPACE
  labels:
    app: prometheus
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: server
  template:
    metadata:
      labels:
        app: prometheus
        component: server
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.retention.time=RETENTIONPERIOD"
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-server
      serviceAccount: prometheus-server
      serviceAccountName: prometheus-server
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 65534:65534 /prometheus"]
        volumeMounts:
          - name: prometheus-storage-volume
            mountPath: /prometheus/
